language: node_js
node_js:
  - "stable"


script:
  - echo "Starting build..."
  - npm install
  - npm test

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  
  local_dir: build
  on:
    branch: main
