language: node_js
node_js:
  - "14"  # Use a stable version of Node.js
cache:
  directories:
    - node_modules
install:
  - npm install  # Install project dependencies
script:
  - npm run build  # Run the build script defined in package.json
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
