language: node_js
node_js:
  - "18"  # Use a compatible Node.js version
install:
  - npm install  # Install project dependencies
script:
  - npm run build  # Adjust according to your build command
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
